name: Deploy SAM Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Check Required Files
        run: |
          if [ ! -d "oppgave-1-2024" ]; then
            echo "Required directory oppgave-1-2024 is missing!"
            exit 1
          fi
          if [ ! -f "oppgave-1-2024/template.yaml" ]; then
            echo "Required template.yaml file is missing in oppgave-1-2024 directory!"
            exit 1

      - name: Deploy SAM Application
        working-directory: exam-oppgave-1
        run: |
          sam build
          sam deploy --no-confirm-changeset --stack-name exam-oppgave-1 --capabilities CAPABILITY_IAM --force-upload || echo "No changes to deploy"

      - name: Fetch and Display API URL
        id: fetch_api_url
        run: |
          api_url=$(aws cloudformation describe-stacks --stack-name exam-oppgave-1 --region eu-west-1 --query "Stacks[0].Outputs[?OutputKey=='ImageGenerationApi'].OutputValue" --output text)
          echo "API Gateway URL is $api_url"
          echo "::set-output name=api_url::$api_url"

      - name: Display API URL
        run: |
          echo "Your API Gateway URL is: ${{ steps.fetch_api_url.outputs.api_url }}"
