name: Deploy SAM Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build SAM Application
        working-directory: exam-oppgave-1
        run: |
          sam build

      - name: Deploy SAM Application
        working-directory: exam-oppgave-1
        run: |
          sam deploy --no-confirm-changeset --stack-name couch-explorers-lambda-rem-2024 --capabilities CAPABILITY_IAM --force-upload --no-fail-on-empty-changeset || echo "No changes to deploy"

      - name: Fetch and Display API Gateway URL
        run: |
          echo "Fetching API Gateway URL..."
          api_url=$(aws cloudformation describe-stacks --stack-name couch-explorers-lambda-rem-2024 --region ${{ env.AWS_REGION }} --query "Stacks[0].Outputs[?OutputKey=='ImageGenerationApi'].OutputValue" --output text)
          echo "API Gateway URL is: $api_url"
          echo "API_GATEWAY_URL=$api_url" >> $GITHUB_ENV

      - name: Debug CloudFormation Outputs
        run: |
          aws cloudformation describe-stacks --stack-name couch-explorers-lambda-rem-2024 --region ${{ env.AWS_REGION }} --query "Stacks[0].Outputs" --output table

      - name: Display API Gateway URL
        run: |
          echo "Your API Gateway URL is: ${{ env.API_GATEWAY_URL }}"
