name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set version
        id: version
        run: echo "VERSION=v1.0.0" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/java-sqs-client:latest ./java_sqs_client
          docker tag ${{ secrets.DOCKER_USERNAME }}/java-sqs-client:latest ${{ secrets.DOCKER_USERNAME }}/java-sqs-client:${{ env.VERSION }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/java-sqs-client:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/java-sqs-client:${{ env.VERSION }}
