name: Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build the Docker image with multiple tags
    - name: Build Docker Image
      run: |
        # Define the semantic version (can be updated based on releases)
        VERSION="v1.0.0"
        
        # Build and tag the Docker image
        docker build -t ${{ secrets.DOCKER_USERNAME }}/java-sqs-client:latest .
        docker tag ${{ secrets.DOCKER_USERNAME }}/java-sqs-client:latest ${{ secrets.DOCKER_USERNAME }}/java-sqs-client:${VERSION}

    # Step 4: Push the Docker image with both tags
    - name: Push Docker Image
      run: |
        # Push both the latest and versioned tags
        docker push ${{ secrets.DOCKER_USERNAME }}/java-sqs-client:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/java-sqs-client:${VERSION}
