name: Terraform Deploy

on:
  push:
    branches:
      - main
      - '**'

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-1
      TF_VAR_bucket: pgr301-2024-terraform-state

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0
          
      # Step 4: Create the Lambda Zip
      - name: Create Lambda Zip
        working-directory: infra/lambda
        run: zip lambda_sqs.zip lambda_sqs.py

      # Step 5: Terraform Init
      - name: Terraform Init
        working-directory: infra
        run: terraform init

      # Step 6: Terraform Plan (For all branches, including main)
      - name: Terraform Plan
        working-directory: infra
        run: terraform plan

      # Step 7: Terraform Apply (For main branch only)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: infra
        run: terraform apply -auto-approve
